server:
  port: 8080

spring:
  datasource:
    name: mydata
    url: jdbc:mysql://47.106.215.255:3306/schoolDemo?serverTimezone=GMT%2B8&useSSL=false
    username: test_oilpea_xyz
    password: s5NpiMsmYp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
  resources:
mybatis:
  mapper-locations: classpath:/mapping/*.xml  #classpath就是应用程序resources的路径
  type-aliases-package: xyz.oilpea.schooldemo.demo.pojo
